APPCAFE-02: Tableview with mocked data
1699kratos/CafePrices pull request #1
Opened 2021-10-22 22:43 UTC by 1699kratos

## ISSUE:
* https://trello.com/c/lG01QCS5

## FIX:
* Added a navigation controller
* Added mocked data to the tableView
* Tested in different iphone models
 
## EVIDENCES:
![image](https://user-images.githubusercontent.com/49655011/138530634-2413b8f3-db0c-4c7b-a1cf-9c3309f2a304.png)

![image](https://user-images.githubusercontent.com/49655011/138533894-501a7c47-8e99-4c00-b642-936396e06803.png)

2021-10-22 22:55 UTC, hachiosaki requested changes

2021-10-22 22:55 UTC, hachiosaki commented on CafePrices/CafePrices/CafeteriasViewController.swift
> +
delete empty lines

2021-10-22 22:55 UTC, hachiosaki commented on CafePrices/CafePrices/TableViewCell.swift
> +
delete empty lines

2021-10-22 22:55 UTC, hachiosaki commented on CafePrices/CafePrices/cafeteria.swift
> +    init(cafeteriaName: String, cafeteriaImage: String){
add a space after String)

2021-10-22 22:56 UTC, hachiosaki requested changes

2021-10-22 22:56 UTC, hachiosaki commented on CafePrices/CafePrices/CafeteriasViewController.swift
> +
Remember that the button that leads us to the collection view is no longer needed, please delete it and later on use the didSelectRow method

2021-10-22 22:58 UTC, 1699kratos commented on CafePrices/CafePrices/CafeteriasViewController.swift
> +
done

2021-10-22 22:58 UTC, 1699kratos commented on CafePrices/CafePrices/TableViewCell.swift
> +
done

2021-10-22 23:00 UTC, 1699kratos commented on CafePrices/CafePrices/cafeteria.swift
> +    init(cafeteriaName: String, cafeteriaImage: String){
why just at the end and not also at the start ?

2021-10-22 23:04 UTC, 1699kratos commented on CafePrices/CafePrices/CafeteriasViewController.swift
> +
okey

2021-10-22 23:05 UTC, hachiosaki commented on CafePrices/CafePrices/cafeteria.swift
> +    init(cafeteriaName: String, cafeteriaImage: String){
for better understanding

2021-10-22 23:06 UTC, 1699kratos commented on CafePrices/CafePrices/cafeteria.swift
> +    init(cafeteriaName: String, cafeteriaImage: String){
okey

2021-10-23 02:16 UTC, hachiosaki requested changes
<img width="517" alt="Captura de Pantalla 2021-10-22 a la(s) 21 12 35" src="https://user-images.githubusercontent.com/89816895/138538781-de6a4e49-ea31-4fcb-a7ef-741962afe950.png"> 
Remove the segue, this was not required.

2021-10-23 02:16 UTC, hachiosaki commented on CafePrices/CafePrices/cafeteria.swift
> +    init(cafeteriaName: String, cafeteriaImage: String ){
Sorry if I didn't explain myself, but this was not what I asked for. The space goes between ") {" not between the word and the parenthesis .

2021-10-23 23:09 UTC, hachiosaki requested changes
Good job

2021-10-23 23:10 UTC, merged