APPCAFE-03: When selecting a row it shows CollectionViewController with mocked data
1699kratos/CafePrices pull request #2
Opened 2021-10-24 00:09 UTC by 1699kratos

## ISSUE:
* https://trello.com/c/PACum6Dn

## FIX:
* Collection View  with mocked data proved in different iphone models
* Function to show Collection View from TableView Controller

## Evidences:
![image](https://user-images.githubusercontent.com/49655011/138575011-1cb008cd-9792-412d-8bf0-c8e867341c54.png)

2021-10-24 18:02 UTC, hachiosaki requested changes

2021-10-24 18:02 UTC, hachiosaki commented on CafePrices/CafePrices/CafeteriasViewController.swift
>      func tableView(_ tableView: UITableView, didSelectRowAt indexPath: IndexPath) {
I think this method can be improved: first making sure that your main.storyboard exist and removing the optional value so it's "storyboard." instead of "storyboard?." we do that creating a reference with the name of your storyboard like this:
 let storyboard = UIStoryboard(name: "Main", bundle: nil)
second, remember that you can't force unwrap because this may cause a break, so I recommend using guard let. I remade the method so this is an idea of what I just told you:
<img width="634" alt="Captura de Pantalla 2021-10-24 a la(s) 12 58 45" src="https://user-images.githubusercontent.com/89816895/138606769-38a0b66b-aff0-486f-85d5-f0ab2aaae706.png">

as you can see first I make sure that my storyboard is referenced and that makes it non optional, then I use a guard let to get rid of the force unwrap in the "pushViewController(vc!)" part. Hope it helps
*Always let an empty line after the guard let statement

2021-10-24 18:02 UTC, hachiosaki commented on CafePrices/CafePrices/MenuViewController.swift
> +class MenuViewController: UIViewController, UICollectionViewDataSource, UICollectionViewDelegate,UICollectionViewDelegateFlowLayout  {
In the tableview controller you have the methods and delegates inside of an extension and also you have your vars on the top of the class and you already are working with objects so, why this class is the opposite? I think you should keep this structure. MenuViewController has the viewdidload method and collectionview IBOutlet till the end and you did not make a "producto" model or used extension. You should keep this structure if you already worked the other class that way: 
Evidences:
| TableViewController | CollectionViewController|
| ------------- | ------------- |
|<img width="702" alt="Captura de Pantalla 2021-10-24 a la(s) 12 59 15" src="https://user-images.githubusercontent.com/89816895/138606717-1024c976-06d4-4b5e-be33-ff85729573ca.png"> |<img width="703" alt="Captura de Pantalla 2021-10-24 a la(s) 12 49 33" src="https://user-images.githubusercontent.com/89816895/138606449-d25afe3b-d20a-427e-ba31-6a4d15afab4f.png">|

2021-10-24 18:02 UTC, hachiosaki commented on CafePrices/CafePrices/MenuViewController.swift
> +
At the end of this line you have two spaces instead of one (before the bracket).

2021-10-24 18:02 UTC, hachiosaki commented on CafePrices/CafePrices/CafeteriasViewController.swift
delete line 18, is empty

2021-10-25 22:55 UTC, 1699kratos commented on CafePrices/CafePrices/MenuViewController.swift
> +class MenuViewController: UIViewController, UICollectionViewDataSource, UICollectionViewDelegate,UICollectionViewDelegateFlowLayout  {
okay, thanks

2021-10-25 22:56 UTC, 1699kratos commented on CafePrices/CafePrices/MenuViewController.swift
> +
okey

2021-10-25 22:57 UTC, 1699kratos commented on CafePrices/CafePrices/CafeteriasViewController.swift
done

2021-10-25 23:12 UTC, 1699kratos commented on CafePrices/CafePrices/CafeteriasViewController.swift
>      func tableView(_ tableView: UITableView, didSelectRowAt indexPath: IndexPath) {
a lot of thanks! im new in this language so i learn a lot everyday, thanks!

2021-10-26 02:50 UTC, hachiosaki requested changes
Is this correct? this is the iPhone 13 max and I think here the image should be bigger or more close to the center, to me it looks closer to the left and right edges, take a look closer, it doesn't look like in the iPhone 12 mini image you attached.
<img width="387" alt="Captura de Pantalla 2021-10-25 a la(s) 21 54 47" src="https://user-images.githubusercontent.com/89816895/138801157-83ff76c8-b271-4f6d-9ae2-2020096f4efa.png">

2021-10-26 02:50 UTC, hachiosaki commented on CafePrices/CafePrices/CafeteriasViewController.swift
> +            else{
please add a space after the else word, or... do it like the image I left

2021-10-26 02:50 UTC, hachiosaki commented on CafePrices/CafePrices/CafeteriasViewController.swift
<img width="425" alt="Captura de Pantalla 2021-10-25 a la(s) 21 49 24" src="https://user-images.githubusercontent.com/89816895/138800594-b7b60c76-3a50-45da-b475-da03a973850a.png">
I still see it

2021-10-26 16:44 UTC, 1699kratos commented on CafePrices/CafePrices/CafeteriasViewController.swift
sorry

2021-10-26 16:46 UTC, 1699kratos commented on CafePrices/CafePrices/CafeteriasViewController.swift
> +            else{
okey

2021-10-27 00:02 UTC, hachiosaki approved these changes

2021-10-27 00:04 UTC, merged